Repository Jeong-Reminder/reminder-backend, pull requests merged in 2024-08, with the labels that each got.

#56 feat : 경진대회 entity 추가
  Dockerfile
  build.gradle
  src/main/java/com/example/backend/controller/announcement/AnnouncementController.java
  src/main/java/com/example/backend/model/entity/announcement/ContestCategory.java
  src/main/java/com/example/backend/model/repository/announcement/AnnouncementRepository.java
  src/main/java/com/example/backend/model/repository/announcement/ContestCategoryRepository.java
  src/main/java/com/example/backend/service/admin/AdminImplService.java
  src/main/java/com/example/backend/service/announcment/AnnouncementService.java
  src/main/java/com/example/backend/service/announcment/impl/AnnouncementServiceImpl.java
  src/main/java/com/example/backend/service/notification/FCM/FCMService.java
Labels: enhancement

#57 fix : #54 file 코드 수정
  src/main/java/com/example/backend/config/SecurityConfig.java
  src/main/java/com/example/backend/controller/announcement/AnnouncementController.java
  src/main/java/com/example/backend/controller/announcement/FileController.java
  src/main/java/com/example/backend/dto/announcement/AnnouncementRequestDTO.java
  src/main/java/com/example/backend/dto/announcement/AnnouncementResponseDTO.java
  src/main/java/com/example/backend/dto/announcement/FileResponseDTO.java
  src/main/java/com/example/backend/dto/comment/CommentRequestDTO.java
  src/main/java/com/example/backend/model/entity/announcement/Announcement.java
  src/main/java/com/example/backend/model/entity/announcement/File.java
  src/main/java/com/example/backend/service/announcment/AnnouncementService.java
  src/main/java/com/example/backend/service/announcment/FileService.java
  src/main/java/com/example/backend/service/announcment/impl/AnnouncementServiceImpl.java
  src/main/java/com/example/backend/service/announcment/impl/FileServiceImpl.java
  src/test/java/com/example/backend/comment/dto/CommentRequestDTOTest.java
  src/test/java/com/example/backend/comment/dto/CommentResponseDTOTest.java
  src/test/java/com/example/backend/comment/model/entity/CommentTest.java
  src/test/java/com/example/backend/comment/model/repository/CommentRepositoryTest.java
  src/test/java/com/example/backend/comment/service/CommentServiceImplTest.java
  src/test/java/com/example/backend/recommend/controller/RecommendControllerTest.java
  src/test/java/com/example/backend/recommend/dto/RecommendRequestDTOTest.java
  src/test/java/com/example/backend/recommend/dto/RecommendResponseDTOTest.java
  src/test/java/com/example/backend/recommend/model/entity/RecommendTest.java
  src/test/java/com/example/backend/recommend/model/repository/RecommendRepositoryTest.java
  src/test/java/com/example/backend/recommend/service/RecommendServiceImplTest.java
Labels: documentation

#68 fix : 파일, 이미지 조회 오류 수정
  src/main/java/com/example/backend/controller/announcement/AnnouncementController.java
  src/main/java/com/example/backend/dto/announcement/AnnouncementDetailResponseDTO.java
  src/main/java/com/example/backend/dto/announcement/AnnouncementResponseDTO.java
  src/main/java/com/example/backend/dto/announcement/FileResponseDTO.java
  src/main/java/com/example/backend/dto/announcement/ImageResponseDTO.java
  src/main/java/com/example/backend/model/entity/announcement/File.java
  src/main/java/com/example/backend/model/entity/announcement/Image.java
  src/main/java/com/example/backend/service/announcment/AnnouncementService.java
  src/main/java/com/example/backend/service/announcment/FileService.java
  src/main/java/com/example/backend/service/announcment/impl/AnnouncementServiceImpl.java
Labels: bug

#73 feat : 관리자용 팀전체 조회, 사용자 팀조회 추가
  src/main/java/com/example/backend/controller/admin/AdminController.java
  src/main/java/com/example/backend/dto/member/MemberProfileResponseDTO.java
  src/main/java/com/example/backend/model/repository/recruitmentteam/TeamMemberRepository.java
  src/main/java/com/example/backend/service/admin/AdminImplService.java
  src/main/java/com/example/backend/service/admin/AdminService.java
  src/main/java/com/example/backend/service/member/MemberProfileImplService.java
  src/test/java/com/example/backend/comment/model/entity/CommentTest.java
  src/test/java/com/example/backend/comment/model/repository/CommentRepositoryTest.java
Labels: enhancement

#79 fix : #78 filecontroller와 imagecontroller 인코딩 수정
  src/main/java/com/example/backend/controller/announcement/FileController.java
  src/main/java/com/example/backend/controller/announcement/ImageController.java
Labels: documentation
